import type { NextPage } from "next";
import Head from "next/head";

import {
  GoogleAuthProvider,
  auth,
  signInWithPopup,
  useSession,
} from "@acme/auth";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const session = useSession();
  return (
    <>
      <Head>
        <title>Better Alexa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <div className="container mt-12 flex flex-col items-center justify-center gap-4 px-4 py-8">
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            Better <span className="text-pink-400">Alexa</span>
          </h1>
          {!session.user && (
            <button
              onClick={() => {
                const provider = new GoogleAuthProvider();
                void signInWithPopup(auth, provider);
              }}
            >
              Sign in
            </button>
          )}
          {session.user && (
            <div>
              <p>{session.user.displayName}</p>
              <p>{session.user.email}</p>
              <Hidden />

              <button
                onClick={() => {
                  void auth.signOut();
                }}
              >
                Sign out
              </button>
            </div>
          )}
        </div>
      </main>
    </>
  );
};

const Hidden = () => {
  const { data } = api.auth.getSecretMessage.useQuery();

  return (
    <div>
      <h1>Secret:</h1>
      <p>{data ?? "error"}</p>
    </div>
  );
};

export default Home;
