/* eslint-disable @typescript-eslint/no-misused-promises */
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

import { useSession } from "@acme/auth";

import { api } from "~/utils/api";

const SpotifyConnect: NextPage = () => {
  const session = useSession();
  const router = useRouter();
  const { mutateAsync } = api.auth.createSpotifyAuth.useMutation();
  return (
    <>
      <Head>
        <title>Better Alexa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <div className="container mt-12 flex flex-col items-center justify-center gap-4 px-4 py-8">
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            Better <span className="text-pink-400">Alexa</span>
          </h1>
          {session.loading && <div>Loading...</div>}
          {!session.loading && !session.user && (
            <span className="ml-2 text-sm font-semibold text-gray-400">
              You need to sign in first!
            </span>
          )}
          {session.user && (
            <button
              className="rounded-lg bg-gray-700 px-3 py-2 text-sm font-semibold text-white hover:bg-gray-800"
              onClick={async () => {
                const url = await mutateAsync();
                void router.push(url);
              }}
            >
              Connect spotify
            </button>
          )}
        </div>
      </main>
    </>
  );
};

export default SpotifyConnect;
