version: "3"

services:
  sample:
    env_file: .env
    restart: always
    build:
      context: apps/sample
      dockerfile: Dockerfile
  cta:
    env_file: .env
    restart: always
    build:
      context: apps/command-to-action
      dockerfile: Dockerfile
  nextjs:
    env_file: .env
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_KEY: ${NEXT_PUBLIC_API_KEY}
        NEXT_PUBLIC_AUTH_DOMAIN: ${NEXT_PUBLIC_AUTH_DOMAIN}
        NEXT_PUBLIC_PROJECT_ID: ${NEXT_PUBLIC_PROJECT_ID}
        NEXT_PUBLIC_STORAGE_BUCKET: ${NEXT_PUBLIC_STORAGE_BUCKET}
        NEXT_PUBLIC_MESSAGING_SENDER_ID: ${NEXT_PUBLIC_MESSAGING_SENDER_ID}
        NEXT_PUBLIC_APP_ID: ${NEXT_PUBLIC_APP_ID}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    environment:
      - SPEECH_TO_TEXT_URL=http://sample:3001/speech-to-text
      - COMMAND_TO_ACTION_URL=http://sample:3001/command-to-action
      - TEXT_TO_SPEECH_URL=http://sample:3001/text-to-speech
    depends_on:
      - sample
      - cta
